Feature: add a method to manually trigger a rescan of the track
iavofficial/IAV_Distortion pull request #102
Opened 2024-08-19 12:53 UTC by m-braunschweig

This PR adds buttons in the StaffUI that trigger a rescan of the track and publishes the newly scanned track to every part of the program that needs to know it.
Closes #97

2024-08-19 15:03 UTC, iav-DaBi commented on src/UserInterface/StaffUI.py
> +            vehicle = environment_mng.get_vehicle_by_vehicle_id(car)
this until line 446 should be done in the environment manager. the environment manager needs the vehicle_id

2024-08-19 15:11 UTC, iav-DaBi commented on test/UnitTest/EnvironmentManagement/EnvironmentManager_Test.py
> +    fleet_ctrl = FleetController()
change to mock-object with spec= FleetController (please check)

2024-08-19 15:15 UTC, iav-DaBi requested changes
plz do your shit

2024-08-19 15:15 UTC, iav-DaBi commented on test/UnitTest/EnvironmentManagement/EnvironmentManager_Test.py
> +    env_manager = EnvironmentManager(fleet_ctrl, configuration_handler=config_mock)
use fleet_ctrl_mock object

2024-08-19 15:15 UTC, iav-DaBi commented on test/UnitTest/EnvironmentManagement/EnvironmentManager_Test.py
> +    fleet_ctrl = FleetController()
change to mock-object with spec= FleetController (please check) and rename to fleet_ctrl_mock

2024-08-20 06:48 UTC, m-braunschweig commented on src/UserInterface/StaffUI.py
> +            vehicle = environment_mng.get_vehicle_by_vehicle_id(car)
Adressed in 87b062ed334dbd25a4f98e470e0428bdfecd5773

2024-08-20 06:56 UTC, m-braunschweig commented on test/UnitTest/EnvironmentManagement/EnvironmentManager_Test.py
> +    fleet_ctrl = FleetController()
Adressed in 083c8a8c1ae29b0f5793236f27500be06d385cec

2024-08-20 10:48 UTC, iav-DaBi approved these changes
all clear

2024-08-20 10:49 UTC, merged